name: Deploy InfraWatch Dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Dev Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: ${{ secrets.DEV_SERVER_SSH_KEY }}
          script: |
            set -e

            APP_DIR="/home/ubuntu/infrawatch-dev"
            REPO_URL="https://github.com/maheshgajjela221/infra-watch.git"
            BRANCH="dev"

            echo "===== Installing required packages ====="

            sudo apt-get update
            sudo apt-get install -y git curl ca-certificates

            if ! command -v docker >/dev/null 2>&1; then
              curl -fsSL https://get.docker.com | sudo sh
              sudo systemctl enable docker
              sudo systemctl start docker
            fi

            if ! sudo docker compose version >/dev/null 2>&1; then
              echo "Installing Docker Compose plugin manually..."
              sudo mkdir -p /usr/local/lib/docker/cli-plugins
              sudo curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
              sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
            fi

            echo "===== Cloning dev branch if not exists ====="

            if [ ! -d "$APP_DIR/.git" ]; then
              cd /home/ubuntu
              sudo rm -rf infrawatch-dev
              git clone -b "$BRANCH" "$REPO_URL" infrawatch-dev
            fi

            echo "===== Pulling latest code ====="

            cd "$APP_DIR"
            git fetch origin "$BRANCH"
            git reset --hard "origin/$BRANCH"

            echo "===== Creating backend .env from GitHub secret ====="

            rm -f backend/.env

            cat > backend/.env <<'EOF'
            ${{ secrets.DEV_BACKEND_ENV }}
            EOF

            echo "===== Validating backend .env ====="

            if [ ! -s backend/.env ]; then
              echo "ERROR: backend/.env is empty. Check GitHub secret DEV_BACKEND_ENV."
              exit 1
            fi

            if ! grep -q "POSTGRES_PASSWORD" backend/.env; then
              echo "ERROR: POSTGRES_PASSWORD missing in backend/.env."
              exit 1
            fi

            echo "===== Deploying containers ====="

            sudo docker compose -p infrawatch-dev down
            sudo docker compose -p infrawatch-dev up -d --build

            echo "===== Cleaning old images ====="

            sudo docker image prune -f

            echo "===== Deployment completed ====="

            sudo docker ps
